services:
  client:
    image: "node:24"
    command: >
      npx screepers-steamless-client@latest
      --package /screeps.nw
      --host 0.0.0.0
      --internal_backend http://screeps:21025/
    volumes:
      - ${SCREEPS_NW_PATH:?"SCREEPS_NW_PATH not set"}:/screeps.nw
      - client-npm-cache:/root/.npm
    ports:
      - "${SCREEPS_PROXY_HOST:-127.0.0.1}:8080:8080/tcp"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "sh", "-c", "curl --fail --silent http://127.0.0.1:8080/"]
      interval: 30s
      timeout: 5s
      start_period: 5s
      start_interval: 5s
      retries: 3

  screeps:
    image: ghcr.io/jomik/screeps-server:edge
    volumes:
      - ./config.yml:/screeps/config.yml
      - screeps-data:/screeps
      - screeps-mods:/screeps/mods
    ports:
      - "${SCREEPS_SERVER_HOST:-127.0.0.1}:21025:21025/tcp"
    environment:
      MONGO_HOST: mongo
      REDIS_HOST: redis
      STEAM_KEY: ${STEAM_KEY:?"Missing steam key"}
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy

  mongo:
    image: mongo:4.4.18
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "sh", "-c", "echo 'db.runCommand(\"ping\").ok' | mongosh localhost:27017/test --quiet"]
      interval: 30s
      timeout: 5s
      start_period: 5s
      start_interval: 5s
      retries: 3

  redis:
    image: redis:7
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      start_period: 5s
      start_interval: 5s
      retries: 3

volumes:
  client-npm-cache:
  redis-data:
  mongo-data:
  screeps-data:
  screeps-mods:
